#ifndef INDEX_NOTATION_H
#define INDEX_NOTATION_H


enum JointSequentialNumberBYNAME
{
  HRR, HRP, HRK,
  HLR, HLP, HLK,
  FRR, FRP, FRK,
  FLR, FLP, FLK,
  NO_OF_JOINTS
};

enum LegSequence
{
  HR, HL, // hind right-left
  FR, FL, // front right-left
  NO_OF_LEGS
};

enum COMMAND {
  NO_ACT = 0,
  CAN_CHECK,
  FIND_HOME,
  MOTOR_ONOFF,
  REF_ONOFF,
  SETTING_DQ_ALIGN,
  SETTING_CUR_NULLING,
  SETTING_HOME_ZERO,
  SETTING_MANUAL_HOME,
  SETTING_REQ_FOC_GAIN,
  SETTING_SET_FOC_GAIN,
  SETTING_REQ_POS_GAIN,
  SETTING_SET_POS_GAIN,
  SETTING_DQ_SHIFT,
  SETTING_DQ_MANUAL,
  SETTING_DQ_MANUAL_ROLL,
  SETTING_IMU_RESET,
  SETTING_JOY_CONNECT,
  SETTING_CURRENT_LIMIT,
  SETTING_DGAIN_MODE,

  MOTION_READY = 100,
  MOTION_GROUND,
  MOTION_HOMMING,
  MOTION_JOG,
  CONTROLMODE_JOINT,
  CONTROLMODE_TASK,
  REFMODE_JOINT,
  REFMODE_TASK,
  CONTROL_START,
  ROBOT_CONTROL_START,
  CONTROL_PARA_SET,
  SAVE_DATA,
  SAVE_DATA_START,
  GAMEPAD_DATA,

  BASIC_TROT_READY = 200,
  BASIC_TROT_START,
  BASIC_TROT_STOP,
  BASIC_TROT_PARA_UPDATE,

  BASIC_BACK_FLIP,
  FALL_RECOVERY,

  MPC_WALK_READY,
  MPC_GAIT_TRANSITION,
  QP_WALK_READY,
  MPC_PARA_UPDATE,
  SWING_LEG_TEST,
  STAIRS_GO,

  AUTO_START = 400,
  DISPLAY_START,
  CMD_BASIC_JSON_SAVE,
  CMD_BASIC_JSON_LOAD,
  CMD_MPC_JSON_SAVE,
  CMD_MPC_JSON_LOAD,
};

enum TASK
{
  NO_TASK,
};


#endif // INDEX_NOTATION_H